name: beben_pos_desktop
description: Beben POS Desktop

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
#  bitsdojo_window: ^0.1.1+1
  cached_network_image: ^3.2.0
  file_picker: ^4.5.0
  flutter_staggered_grid_view: 0.4.0
  flutter_bloc: ^8.0.0
  equatable: ^2.0.0
  # For Restfull API
  dio: ^4.0.0
  pretty_dio_logger: ^1.1.1
  html: ^0.15.0
  flutter_html: ^2.2.1
  logging: ^1.0.1
  awesome_dialog: ^1.3.2
  nav_router:
    git:
      url: https://github.com/chairilrafi11/nav_router
  flutter_luban:
    git:
      url: https://github.com/crazecoder/flutter_luban    
  # another_flushbar: ^1.10.24
  pointycastle: ^3.1.3
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  provider: ^6.0.0
  flutter_secure_storage: ^4.2.1
  path_provider: ^2.0.1
  rxdart: ^0.27.2
  bot_toast: ^4.0.1
  get: ^4.3.8
  flutter_screenutil: ^5.0.0+2
  syncfusion_flutter_barcodes: ^19.3.43
  desktop_window: ^0.3.0
  pdf: ^3.6.0
  flutter_esc_pos_utils: ^0.1.4
  flutter_esc_pos_network: ^0.0.3
  printing: ^5.6.0
  internet_connection_checker: ^0.0.1+3
  uuid: 3.0.5
  window_size:
    git:
      url: https://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size
  #  flutter_secure_storage: ^4.2.1
#  path_provider: ^2.0.3
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
#  process_run: ^0.12.2+1
#  units_converter: ^1.1.1+2
  intl:
  windows_documents: ^1.0.0
#  firebase_messaging: 10.12
#  firebase_core: 10.12
#  firebase_crashlytics: 10.12

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.1
  build_runner: ^2.1.2
  json_serializable: ^4.1.0
  retrofit_generator: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/images/

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
