---
name: On Linux Release
'on':
  push:
    branches:
      - "master"
jobs:
  on-push-main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1.4.0
        with:
          channel: dev
      - run: |
          sudo apt-get -y install clang cmake ninja-build pkg-config libgtk-3-dev libblkid-dev liblzma-dev
          sudo apt-get -y install libjsoncpp-dev
          sudo apt-get -y upgrade
          sudo apt-get -y update
      - name: Enable Linux
        run: |
          flutter clean
          flutter create .
          flutter config --enable-linux-desktop
          flutter pub get
          flutter packages get
          flutter doctor -v
      - name: Build Linux app
        run: flutter build linux